#!/bin/sh

export CODE_DIR=$PWD
export FINAL_OBJ=$PWD/obj/

if [ "$1" = "" ]; then
	echo "Building TM Virtual Lib"
	make -C .
else
	echo "Cleaning SIM Lib"
	make $1 -C .
fi
if [ $? = 0 ]; then
	echo "Sucessfully Done"
else
	echo "Build Failure"
fi
