#!/bin/sh

export CODE_DIR=$PWD
export FINAL_OBJ=$PWD/build/obj/

cd ${CODE_DIR}/TechMindsLib
./tmlib_build $1
cd -

if [ "$1" = "" ]; then
	echo "Building SIM Lib"
	make -C ./build
else
	echo "Cleaning SIM Lib"
	make $1 -C ./build
fi
if [ $? = 0 ]; then
	mv ./build/Switch.exe ./
	sync
	echo "Sucessfully Done"
else
	echo "Build Failure"
fi
